api_movie:
    type: rest
    resource: Movie\MovieBundle\Controller\MovieAPIController
    name_prefix: api_movie_
    prefix: /

api_review:
    type: rest
    resource: Movie\MovieBundle\Controller\ReviewAPIController
    name_prefix: api_review_
    prefix: /

