movie_index:
    path:     /
    defaults: { _controller: MovieMovieBundle:Page:index }

movie_show:
    path: /movie/show/{id}
    defaults: { _controller: MovieMovieBundle:Page:show, id: id }
    requirements:
        id: '\d+'

movie_search:
    path: /movie/search
    defaults: { _controller: MovieMovieBundle:Page:search }

movie_delete:
    path: /movie/delete/{id}
    defaults: { _controller: MovieMovieBundle:Page:delete, id: id }

movie_edit:
    path: /movie/edit/{id}
    defaults: { _controller: MovieMovieBundle:Page:editMovie, id: id }

movie_about:
    path: /about
    defaults: { _controller: MovieMovieBundle:Page:about }
    requirements:

movie_login:
    path: /login
    defaults: { _controller: MovieMovieBundle:Page:login }
    requirements:

movie_register:
    path: /register
    defaults: { _controller: MovieMovieBundle:Page:register }
    requirements:

movie_new:
    path: /movie/new
    defaults: { _controller: MovieMovieBundle:Page:new }
    requirements:

movie_user:
    path: /user-page/{id}
    defaults: { _controller: MovieMovieBundle:Page:userPage }
    requirements:


review_view:
    path:     /review/{id}
    defaults: { _controller: MovieMovieBundle:Review:view }

review_create:
    path:     review/create/{id}
    defaults: { _controller: MovieMovieBundle:Review:create, id: id }
    requirements:
        id: '\d+'

review_edit:
    path:     /review/edit/{id}
    defaults: { _controller: MovieMovieBundle:Review:edit, id: id }

review_delete:
    path:     /review/delete
    defaults: { _controller: MovieMovieBundle:Review:delete }
