api_movie:
    type: rest
    resource: Movie\MovieBundle\Controller\MovieAPIController
    name_prefix: api_movie_
    prefix: /

api_review:
    type: rest
    resource: Movie\MovieBundle\Controller\ReviewAPIController
    name_prefix: api_review_
    prefix: /

api_joind:
    type: rest
    resource: Movie\MovieBundle\Controller\JoindInController
    name_prefix: api_joind_
    prefix: /

api_omdb:
    type: rest
    resource: Movie\MovieBundle\Controller\OMDBController
    name_prefix: api_omdb_
    prefix: /

