fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

movie_movie:
    resource: "@MovieMovieBundle/Resources/config/routing.yml"
    prefix:   /

movie_api:
    type: rest
    resource: "@MovieMovieBundle/Resources/config/routing_api.yml"
    prefix: /api/v1

review_api:
    type: rest
    resource: "@MovieMovieBundle/Resources/config/routing_api.yml"
    prefix: /api/v1

joind_api:
    type: rest
    resource: "@MovieMovieBundle/Resources/config/routing_api.yml"
    prefix: /api/v1

omdb_api:
    type: rest
    resource: "@MovieMovieBundle/Resources/config/routing_api.yml"
    prefix: /api/v1

app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /logout

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

